# PyTorch Tutoria: 02 Dataset and Iterator
## Overview 
In this tutorial, we will cover the basics of constructing dataset and iterators so that we can train models using gradient descent. 

The best tutorial can be found in the official website (https://pytorch.org/tutorials/beginner/data_loading_tutorial.html).

In [1]:
import torch
from torch.utils.data import Dataset, DataLoader

In [2]:
class MyStupidDataset(Dataset):#继承Dataset类
    def __init__(self):
        super(MyStupidDataset, self).__init__()
        self.data = torch.randn([1024, 10, 10])#1024个10*10的Tensor
    def __len__(self):
        return 1024
    def __getitem__(self, idx):
        return self.data[idx, :, :] 

In [5]:
my_stupid_dataset = MyStupidDataset()

In [6]:
my_data_loader = DataLoader(my_stupid_dataset, batch_size=64, shuffle=True)#my_stupid_dataset从哪里导入？batch_size抽几个数？shuffle是否打乱？

In [7]:
for i in my_data_loader:
    print(i)

tensor([[[-7.0444e-01,  2.0250e-03, -8.0713e-01,  ...,  4.4728e-01,
          -5.9955e-01,  1.4517e+00],
         [ 1.6289e+00,  8.1193e-01, -8.5433e-01,  ...,  7.6278e-01,
          -1.7856e+00, -5.0998e-01],
         [ 1.3534e-01, -7.9825e-01, -4.3691e-01,  ..., -5.4642e-01,
           9.1890e-02,  2.9590e-01],
         ...,
         [-1.0740e+00, -1.3540e+00,  2.1577e+00,  ...,  6.7907e-01,
           4.9143e-01,  1.3989e-01],
         [-5.6946e-01, -5.9137e-01, -2.2322e+00,  ..., -1.2450e+00,
          -1.5081e+00,  7.5247e-01],
         [-1.3133e+00, -1.2468e+00,  1.7244e+00,  ...,  1.9780e+00,
           5.5562e-01,  3.4395e-01]],

        [[-1.0572e+00,  9.7624e-01, -1.2408e+00,  ...,  8.7772e-02,
           1.5185e+00,  3.0432e-02],
         [-1.7565e+00, -1.5685e+00,  9.1671e-01,  ..., -1.0017e+00,
           1.4933e-01,  1.0740e+00],
         [ 1.0302e+00, -5.1530e-01, -1.2763e+00,  ..., -1.3210e+00,
          -1.4197e+00, -6.2994e-01],
         ...,
         [ 1.1574e+00,  1

In [6]:
# A common Pattern
class MyDictDataset(Dataset):
    def __init__(self):
        super(MyDictDataset, self).__init__()
        self.x = torch.randn(1024, 10)
        self.y = torch.randn(1024)
    def __len__(self):
        return 1024
    def __getitem__(self, idx):
        return {'x':self.x[idx,:],'y':self.y[idx]}

In [7]:
my_dict_dataset = MyDictDataset()
my_data_loader = DataLoader(my_dict_dataset, batch_size=64, shuffle=True)
for batch in my_data_loader:
    print(batch['x'])
    print(batch['y'])

tensor([[ 9.8082e-01, -2.8023e-01, -1.2525e+00, -3.6965e-01,  1.8818e-01,
         -1.6073e+00,  9.3212e-01, -6.9147e-01, -3.3545e-02,  2.2559e-01],
        [-2.1869e+00,  4.7473e-01,  3.7868e-03, -4.0867e-01,  1.6978e+00,
          2.4035e+00,  1.2119e+00,  1.6577e-01, -6.0310e-01, -2.3801e-01],
        [ 1.0599e-02, -3.6531e-01, -6.1027e-01,  9.3681e-01, -1.5954e-01,
          1.0503e+00,  2.0387e+00,  3.9710e-01, -1.1716e+00,  9.8480e-01],
        [ 2.4740e-01,  2.1640e-01,  6.1070e-01, -5.7585e-01,  2.1275e+00,
         -5.2992e-01, -4.9332e-01,  4.5006e-02,  4.5715e-02, -1.1354e+00],
        [-1.1164e+00,  5.4933e-01,  1.8641e+00,  1.8800e+00, -2.9633e-01,
          5.0617e-01, -8.1875e-02,  1.3482e+00,  1.6780e+00, -1.9506e-01],
        [ 9.7563e-01,  6.3292e-02,  7.3559e-01,  1.1803e+00,  1.6200e+00,
          3.4809e-01, -7.0261e-01, -9.4948e-01,  5.2532e-01,  7.3993e-01],
        [-4.5824e-01, -2.0280e-01, -3.5606e-01,  2.2650e-02, -4.9376e-01,
          2.2427e-02,  3.7425e-0

tensor([[-1.1948e-01, -3.3844e-01, -1.0990e+00, -1.3620e+00,  1.5962e+00,
          4.0207e-01,  1.7554e+00,  7.8194e-01,  2.3851e+00, -1.2792e+00],
        [ 6.7720e-01, -2.3028e-02,  2.8391e-01, -2.6081e-01, -3.0357e-01,
          3.0295e-01,  6.1715e-01, -1.2074e+00, -1.3609e+00,  5.9287e-01],
        [-1.3126e+00, -4.1483e-01, -5.0597e-01,  3.7362e-01, -1.5332e+00,
         -1.1719e+00,  9.1465e-01, -1.8734e+00, -5.8218e-01,  1.3103e+00],
        [-1.3817e-01, -2.3106e-01,  1.6226e+00, -1.0186e+00, -7.0677e-01,
         -1.1695e+00,  1.8919e+00, -8.8633e-01, -1.0983e+00,  1.5716e+00],
        [ 1.2546e-01, -3.1749e-03,  3.7619e-01, -1.2693e+00,  8.4616e-01,
         -3.2801e-01,  7.9962e-02, -2.6675e-01, -5.1432e-01,  7.6496e-01],
        [-1.2961e+00, -7.1657e-01, -6.0917e-01, -7.5575e-01, -6.5881e-01,
         -2.5216e-01, -5.5920e-01,  1.9096e-01,  2.0621e+00, -4.4936e-01],
        [ 2.9514e+00, -1.0681e+00, -1.4430e+00,  1.8782e-01, -3.0654e-01,
          5.3518e-01,  6.8356e-0

In [8]:
from torch.utils.data import TensorDataset
x = torch.randn(10,100)
y = torch.randn(10)
tensor_dataset = TensorDataset(x, y)

为什么要写自己的Dataset?
    文本非常大，我们可能要做一个iterator，有几种方法来实现：①直接打开该文件，读取其中的一部分文本，直接用IO的方式来写，这样保证了我们读取数据所占用的内存或显存较小，但读写速度较慢②全部读到内存，在内存中做iteration③每次做iteration时，重新分词，然后对其对应的token进行更新，通过写自己的Dataset的方式，可以把操作在不同阶段进行处理。例如，每次重新读取文本比较慢，可以先将其对应的Embedding先找出来，自己构建一个数据集，但这样做的问题在于占用大量内存和显存，读入速度慢，但可以节约找embedding的layer的时间